version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    env_file: .env
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always


  drupal:
    build: ./docker/drupal
    depends_on:
      - db
    restart: always
    volumes:
      - ./drupal-data/modules:/var/www/html/modules
      - ./drupal-data/themes:/var/www/html/themes
      - ./drupal-data/files:/opt/drupal/web/sites/default/files
    env_file: .env
    ports:
      - "${EXPOSED_PORT}:80"

  pma:
    build: ./docker/pma
    restart: always
    ports:
      - "${PMA_PORT}:80"
    env_file: .env

